name: Docker Build Nightly

on:
  push:
    branches:
      - feature/github-actions-docker
  pull_request:
    branches:
      - develop

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: teamveganat/member-api
          # dockerfile: ../../Dockerfile
          tag_with_ref: true
          tag_with_sha: true
          tags: nightly
